### ISSUE TITLE
Umbrella Ticket

### ISSUE THREAD

**Issue by NoahPidding** [awtung/p2-cowboys#42]
Below are all of our tickets, focusing on completing main aspects of the website such as a database and API system, as well as touching up the UI and formatting of HTML pages to ensure everything looks nice.

**Comment by D1935827V** [comment]
https://github.com/awtung/p2-cowboys/issues/39

**Comment by NoahPidding** [comment]
Noah's Ticket: ([link](https://github.com/awtung/p2-cowboys/issues/2))
- [x] Combine home page and map so it's one page with title and creators along with buttons for navigation
- Add light and dark mode buttons to:
- [x] About Us Page
- [x] Home Page
- [x] Random API Page
- [x] Saloon Page

Tangibles (video): [Home Road](https://www.youtube.com/watch?v=xAdC4N56ktU)
Home Road Code: 
- [Home Road](https://github.com/awtung/p2-cowboys/blob/3a507ddc053ce8fa3b11495f15d446de48d7a43c/social/home/templates/homenav.html#L1-L107)

Tangibles (video): [Dark Mode](https://www.youtube.com/watch?v=0oqrmQ7vnZE)
Dark Mode Code:
- [About Us](https://github.com/awtung/p2-cowboys/blob/3a507ddc053ce8fa3b11495f15d446de48d7a43c/social/home/templates/aboutus.html#L67-L84)
- [Home Page](https://github.com/awtung/p2-cowboys/blob/3a507ddc053ce8fa3b11495f15d446de48d7a43c/social/home/templates/homenav.html#L10-L17)
- [Random API Page](https://github.com/awtung/p2-cowboys/blob/3a507ddc053ce8fa3b11495f15d446de48d7a43c/social/home/templates/randomapi.html#L25-L42)
- [Saloon Page](https://github.com/awtung/p2-cowboys/blob/3a507ddc053ce8fa3b11495f15d446de48d7a43c/saloon/templates/saloon.html#L13-L104)

Progress on Final Project Requirements: 
- This ticket helps with the theme and user interactions of the website, as the main home road page is a cool and creative navigation feature for the website, which is a main part of our theme. Also dark mode is a cool feature to have on a website which users might prefer over light mode, which also may enhance the theme. .

**Comment by nathanlee27** [comment]
https://github.com/awtung/p2-cowboys/issues/40#issue-899818284

**Comment by awtung** [comment]
[Aidens Ticket](https://github.com/awtung/p2-cowboys/issues/41)
